
###

PUT http://localhost:3006/change-password
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3Jpbml2YXN1bHUiLCJpYXQiOjE3MzI0MzE0MDB9.qBA3mJavr39luZ_ca8GNFxdS7u7mrBSCSJT2uhrdH8g
Content-Type: application/json

{
  "name": "haripriya kanike",
  "oldPassword": "123",
  "newPassword": "haripriya@123"
}

###

GET http://localhost:3006/users/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaGFyaXByaXlhIGthbmlrZSIsImlhdCI6MTczMjQ1ODEyOH0.RK5uLoBDW46rZIhyVeZrUg2I7mV2kW9LOh32MYe9aAc

//todo CRUD OPERATIONS

###
POST http://localhost:3006/todos/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3Jpbml2YXN1bHUiLCJpYXQiOjE3MzI0MzI2NDV9.UE7qGaiZiN-kArBHS0y2rnxpFjOZK72qLzZesPDIRWc
Content-Type:application/json

{
  "todo": "python",
  "status": "inprogress"
}

###
 
DELETE http://localhost:3006/todos/2d8dd74c-fcb1-4ed7-b854-e7d165102acd/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3Jpbml2YXN1bHUiLCJpYXQiOjE3MzI0MzI2NDV9.UE7qGaiZiN-kArBHS0y2rnxpFjOZK72qLzZesPDIRWc

###

GET http://localhost:3006/todos/?status=done
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3Jpbml2YXN1bHUiLCJpYXQiOjE3MzI0MzI2NDV9.UE7qGaiZiN-kArBHS0y2rnxpFjOZK72qLzZesPDIRWc

###

GET http://localhost:3006/todos/085d0e2d-1762-4fce-b806-3503bb53fb13/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3Jpbml2YXN1bHUiLCJpYXQiOjE3MzI0MzI2NDV9.UE7qGaiZiN-kArBHS0y2rnxpFjOZK72qLzZesPDIRWc

###

PUT http://localhost:3006/todos/085d0e2d-1762-4fce-b806-3503bb53fb13/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3Jpbml2YXN1bHUiLCJpYXQiOjE3MzI0MzI2NDV9.UE7qGaiZiN-kArBHS0y2rnxpFjOZK72qLzZesPDIRWc
Content-Type:application/json

{ "status": "done" }